<?php 
$config['id'] = '1'; 
$config['dropbox_email'] = ''; 
$config['dropbox_password'] = ''; 
$config['site_contact_mail'] = 'devaraj@mailinator.com'; 
$config['site_contact_number'] = ''; 
$config['email_title'] = 'HomeStayDnn '; 
$config['demo_ar'] = ''; 
$config['admin_currencyCode'] = 'USD'; 
$config['google_verification'] = ''; 
$config['google_verification_code'] = '<script>  
(function(i,s,o,g,r,a,m){i[\'GoogleAnalyticsObject\']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,\'script\',\'https://www.google-analytics.com/analytics.js\',\'ga\');

  ga(\'create\', \'UA-62671250-3\', \'auto\');
  ga(\'send\', \'pageview\');
</script>

'; 
$config['facebook_link'] = 'https://www.facebook.com/pofitechnologies/'; 
$config['twitter_link'] = 'https://twitter.com/pofitec'; 
$config['pinterest'] = ''; 
$config['googleplus_link'] = 'https://plus.google.com/115490083642952820972/posts'; 
$config['linkedin_link'] = ''; 
$config['rss_link'] = ''; 
$config['youtube_link'] = ''; 
$config['footer_content'] = 'Copyright 2018. HomeStayDnn. All Rights Reserved'; 
$config['logo_image'] = '1bookingz-logo.png'; 
$config['home_logo_image'] = '50x501.png'; 
$config['background_image'] = 'hotel-indigo-tel-aviv-2533439546-2x1.jpg'; 
$config['videoUrl'] = 'https://www.youtube.com/embed/WTgwJDuN1Xk'; 
$config['slider'] = 'on'; 
$config['meta_title'] = 'Vacation Rentals, Homes, Experiences & Places'; 
$config['meta_keyword'] = 'HomestayDNN-Airbnb clone script, a perfect online vacation rental software which helps you to build your own online rental business. Buy now with %'; 
$config['meta_description'] = 'HomestayDNN-Airbnb clone script, a perfect online vacation rental software which helps you to build your own online rental business. Buy now with 100% source code & host in multi domains. ssss'; 
$config['fevicon_image'] = 'bookings-fav2.png'; 
$config['watermark'] = '5050-22.jpg'; 
$config['facebook_api'] = ''; 
$config['facebook_secret_key'] = ''; 
$config['paypal_api_name'] = ''; 
$config['paypal_api_pw'] = ''; 
$config['paypal_api_key'] = ''; 
$config['authorize_net_key'] = ''; 
$config['paypal_id'] = ''; 
$config['paypal_live'] = ''; 
$config['smtp_port'] = '0'; 
$config['smtp_uname'] = ''; 
$config['smtp_password'] = ''; 
$config['consumer_key'] = ''; 
$config['consumer_secret'] = ''; 
$config['google_client_secret'] = 's7Mwjv0wZK5NvlXkbpTRLuDz'; 
$config['google_client_id'] = '16735640491-3dkl9bliclkn1qdlk7lp87l2t62q41vp.apps.googleusercontent.com'; 
$config['google_redirect_url'] = 'https://demo1.homestaydnn.com/google-login'; 
$config['google_redirect_url_db'] = 'https://demo1.homestaydnn.com/ dbbackup/fileUpload.php'; 
$config['google_redirect_url_connect'] = 'https://demo1.homestaydnn.com/ site/invitefriend/google_connect'; 
$config['google_developer_key'] = 'AIzaSyC_ATkeY478Rr3043p6Qq-bbOJ4Ejy8hYk'; 
$config['bing_developer_key'] = 'AtYulzYx60RZrLaeAIegmDWPyTFapdbmbdQCNna68LWTnscAxwyvPTdysAe1L02s'; 
$config['linkedin_app_id'] = '8153l3ugibla11'; 
$config['linkedin_app_key'] = 'upXzhZT17B4JTwAk'; 
$config['facebook_app_id'] = '245697612981928'; 
$config['facebook_app_secret'] = '689da84ae8a622b861dd406daed45ec7'; 
$config['like_text'] = 'Like'; 
$config['unlike_text'] = 'Unlike'; 
$config['liked_text'] = 'Like\'d'; 
$config['banner_text'] = ''; 
$config['site_pagination_per_page'] = '8'; 
$config['dispute_days'] = '1'; 
$config['twilio_account_sid'] = 'AC91ffe2145fe3f1d156e9981d93e2ff3d'; 
$config['twilio_account_token'] = '06123b2a685e534cf7fa72d056693238'; 
$config['twilio_phone_number'] = '+17869016767'; 
$config['google_map_api'] = ''; 
$config['home_title_1'] = ''; 
$config['home_title_2'] = ''; 
$config['home_title_3'] = ''; 
$config['home_title_4'] = ''; 
$config['s3_bucket_name'] = ''; 
$config['s3_access_key'] = ''; 
$config['s3_secret_key'] = ''; 
$config['facebook_share'] = 'http://demo3.pofi5.com/rental/100'; 
$config['popular_pagination_per_page'] = '3'; 
$config['places_pagination_per_page'] = '5'; 
$config['experiences_pagination_per_page'] = '5'; 
$config['wishlist_pagination_per_page'] = '4'; 
$config['image_compress_percentage'] = '100'; 
$config['cancel_hide_days_experience'] = '1'; 
$config['cancel_hide_days_experience_host'] = '1'; 
$config['cancel_hide_days_property'] = '5'; 
$config['cancel_hide_days_property_host'] = '1'; 
$config['admin_country_code'] = '95'; 
$config['twilio_status'] = '1'; 
$config['site_status'] = '1'; 
$config['created'] = '2016-04-15'; 
$config['modified'] = '2019-11-02'; 
$config['admin_name'] = 'admin'; 
$config['email'] = 'devaraj@mailinator.com'; 
$config['admin_type'] = 'super'; 
$config['privileges'] = ''; 
$config['last_login_date'] = '2019-11-02 04:37:55'; 
$config['last_logout_date'] = '2019-05-11 07:28:42'; 
$config['last_login_ip'] = '192.168.0.87'; 
$config['is_verified'] = 'Yes'; 
$config['status'] = 'Active'; 
$config['show_password'] = '9xVars'; 
$config['manual_currency_status'] = '1'; 
$config['exchange_rate_api'] = '667dc414eb1a66d9a1739df4'; 
$config['contact_us_address'] = ''; 
$config['message_pagination_per_page'] = '10'; 
$config['base_url'] = 'http://192.168.0.84/1bookingz/';  ?>